### ISSUE TITLE
My card not found. Quadro M2000M

### ISSUE THREAD

**Issue by darkstaring** [RunGp/Nvidiux#43] opened 2018-12-15 01:05 UTC
NVIDIA Corporation GM107GLM [Quadro M2000M]
not found data ! 

`nvidia-smi -i 0 -q -d POWER

==============NVSMI LOG==============

Timestamp                           : Sat Dec 15 02:04:41 2018
Driver Version                      : 415.22
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Power Samples
        Duration                    : N/A
        Number of Samples           : N/A
        Max                         : N/A
        Min                         : N/A
        Avg                         : N/A

`

**Comment by darkstaring** [comment] 2018-12-15 01:06
what can I do?

NVIDIA Driver Version: 415.22
4.19.8-2-MANJARO
.... ( hashcat benchmark return 60308 H/s with 2500 - WPA-EAPOL-PBKDF2)

**Comment by darkstaring** [comment] 2018-12-15 01:44
I think need upgrade the BIOS version on the video card, but here :
https://www.techpowerup.com/vgabios/
i can't see nmy video card.. 
:(

**Comment by RunGp** [comment] 2018-12-18 06:59
Duplicate of issue #41
Nvidiux doesn't support quadro card.

**Closed as completed by RunGp** 2018-12-18 06:59 UTC
